### ISSUE TITLE
build arm6/7 binaries

### ISSUE THREAD

**Issue by c-nv-s** [jedavies-dev/kiss-aarch64#1]
is it possible to also build arm6/7 binaries for release too.

**Comment by jedavies-dev** [comment]
This port is aarch64 only and I don't have any plans to do an armv6/7 one.

However if you're looking to run software which is only available on 32-bit ARM (e.g. Widevine) on an aarch64 distro, you can do this by setting up a 32-bit chroot.  This allows you to run Chromium/Netflix etc.
