### ISSUE TITLE
Error compiling gnupg1

### ISSUE THREAD

**Issue by Cyberx9901** [jedavies-dev/kiss-aarch64#5]
When I try to compile gnupg1 with the command:
kiss build gnupg1
I have the following result:

checking build system type... aarch64-unknown-linux-gnu
checking host system type... aarch64-unknown-linux-gnu
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... scripts/install-sh -c -d                                                              
checking for gawk... no
checking for mawk... no
checking for nawk... no
checking for awk... awk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
configure: autobuild project... gnupg
configure: autobuild revision... 1.4.23
configure: autobuild hostname... raspberrypi
configure: autobuild timestamp... 20210302-182606
checking for style of include used by make... GNU
checking for gcc... gcc
checking whether the C compiler works... no
configure: error: in `/root/.cache/kiss/proc/21606/build/gnupg1':
configure: error: C compiler cannot create executables           
See `config.log' for more details

and the /root/.cache/kiss/proc/21606/build/gnupg1 folder just doesn't exist when I check
so this is the only log I have

**Comment by jedavies-dev** [comment]
If you build like this:

`KISS_DEBUG=1 kiss b gnupg1`

...then the build directory will be left after the build fails. You can then check config.log.  Looks like an issue with your CFLAGS? Do other packages build OK?

**Comment by Cyberx9901** [comment]
no, all packages give this problem, it was informed by my colleagues that this is caused by the lack of programs like coreutils installed in the base

**Comment by jedavies-dev** [comment]
Please post config.log and we should be able to see what's going on.

**Comment by jedavies-dev** [comment]
No update on this, closing.
